name: CI
on:
  push:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: 14.x-${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Type Check
        run: yarn type-check
      - name: Configure Git Credentials
        if: github.repository == 'n1ru4l/react-use-transition'
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "Github Action"
      - name: Publish
        if: github.repository == 'n1ru4l/react-use-transition'
        run: |
          cd dist
          yarn version --no-git-tag-version --prerelease --preid ${GITHUB_SHA::8}
          yarn publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
